import { StyleSheet } from "react-native";

export default StyleSheet.create({
  background: {
    flex: 1,
    backgroundColor: "#a9c9cc", // Set the background color
    justifyContent: "center",
    alignItems: "center",
    paddingTop: 20,
  },
  container: {
    width: "90%",
    maxWidth: 400,
    borderRadius: 30,
    overflow: "hidden",
  },
  headerImage: {
    width: "100%",
    height: 150,
    backgroundColor: "#ccc",
  },
  logo: {
    position: "absolute",
    top: 16,
    left: 16,
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: "#fff",
    padding: 8,
  },
  appTitleContainer: {
    position: "absolute",
    bottom: -24,
    left: "50%",
    transform: [{ translateX: -50 }],
    backgroundColor: "#2c3e58",
    borderRadius: 30,
    paddingHorizontal: 24,
    paddingVertical: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  appTitle: {
    color: "#fff",
    fontSize: 24,
    fontWeight: "bold",
    fontFamily: "Fredoka One",
  },
  loginBox: {
    backgroundColor: "#a9c9cc",
    paddingTop: 48,
    paddingBottom: 32,
    paddingHorizontal: 24,
    borderRadius: 30,
  },
  input: {
    borderRadius: 30,
    paddingHorizontal: 16,
    paddingVertical: 8,
    backgroundColor: "#fff",
    color: "#2c3e58",
    fontSize: 16,
    marginBottom: 16,
  },
  forgotPassword: {
    textAlign: "right",
    color: "#2c3e58",
    fontSize: 12,
    marginBottom: 16,
  },
  buttonRow: {
    flexDirection: "row",
    gap: 16,
    marginBottom: 16,
  },
  loginButton: {
    flex: 1,
    backgroundColor: "#2c3e58",
    borderRadius: 30,
    paddingVertical: 8,
    alignItems: "center",
  },
  signUpButton: {
    flex: 1,
    backgroundColor: "#2c3e58",
    borderRadius: 30,
    paddingVertical: 8,
    alignItems: "center",
  },
  buttonText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "bold",
  },
  registerText: {
    textAlign: "center",
    color: "#2c3e58",
    fontSize: 12,
    marginBottom: 8,
  },
  petSignUpButton: {
    backgroundColor: "#f0b94f",
    borderRadius: 30,
    paddingVertical: 8,
    alignItems: "center",
    alignSelf: "center",
    width: 120,
  },
  petSignUpText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "bold",
  },
  socialButtonsContainer: {
    backgroundColor: "#2c3e58",
    borderRadius: 30,
    paddingVertical: 16,
    paddingHorizontal: 24,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 16,
  },
  socialButton: {
    backgroundColor: "#fff",
    borderRadius: 30,
    width: 40,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
  },
});